#!/usr/bin/ash

run_hook() {
    local rootdev
    if rootdev="$(resolve_device "$root")" && bcachefs unlock -c "$rootdev" >/dev/null 2>&1
    then
        echo "Unlocking $rootdev:"
        while true
        do
            bcachefs unlock "$rootdev" && break
        done
    fi
}

# vim: set ft=sh ts=4 sw=4 et:
